sonarqube 관련설정 추가 및 테스트 빌드

diff --git a/.github/workflows/devsecops.yaml b/.github/workflows/devsecops.yaml
--- a/.github/workflows/devsecops.yaml
+++ b/.github/workflows/devsecops.yaml
@@ -38,65 +38,67 @@ jobs:
 
       - name: Build and Push Docker Image
         env:
-          DOCKER_USER: ${{ secrets.DOCKER_USER }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         run: |
-          ./gradlew bootBuildImage -x test --imageName=$IMAGE_NAME:${{ github.sha }}
-          echo $DOCKER_PASSWORD | docker login $REGISTRY -u $DOCKER_USER --password-stdin
-          docker push $IMAGE_NAME:${{ github.sha }}
+          ./gradlew build sonar --info
+        # run: |
+        #   ./gradlew bootBuildImage -x test --imageName=$IMAGE_NAME:${{ github.sha }}
+        #   echo $DOCKER_PASSWORD | docker login $REGISTRY -u $DOCKER_USER --password-stdin
+        #   docker push $IMAGE_NAME:${{ github.sha }}
           
-  scan:
-    needs: build-and-push
-    runs-on: ubuntu-20.04
-    steps:
-      - name: Pull Docker Image
-        run: |
-          docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
+  # scan:
+  #   needs: build-and-push
+  #   runs-on: ubuntu-20.04
+  #   steps:
+  #     - name: Pull Docker Image
+  #       run: |
+  #         docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
           
-      - name: Run Trivy vulnerability scanner
-        uses: aquasecurity/trivy-action@master
-        with:
-          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
-          format: 'sarif'
-          output: 'trivy-results.sarif'
-          exit-code: '1'
-          ignore-unfixed: true
-          severity: 'CRITICAL,HIGH'
+  #     - name: Run Trivy vulnerability scanner
+  #       uses: aquasecurity/trivy-action@master
+  #       with:
+  #         image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
+  #         format: 'sarif'
+  #         output: 'trivy-results.sarif'
+  #         exit-code: '1'
+  #         ignore-unfixed: true
+  #         severity: 'CRITICAL,HIGH'
           
-      - name: Upload Trivy scan results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v1
-        with:
-          sarif_file: 'trivy-results.sarif'
+  #     - name: Upload Trivy scan results to GitHub Security tab
+  #       uses: github/codeql-action/upload-sarif@v1
+  #       with:
+  #         sarif_file: 'trivy-results.sarif'
           
-  zap-scan:
-    needs: build-and-push
-    runs-on: ubuntu-20.04
-    steps:        
-      - name: Run Spring Boot application
-        run: |
-          docker run -d -p 8080:8080 --name petclinic ${{ env.IMAGE_NAME }}:${{ github.sha }}
+  # zap-scan:
+  #   needs: build-and-push
+  #   runs-on: ubuntu-20.04
+  #   steps:        
+  #     - name: Run Spring Boot application
+  #       run: |
+  #         docker run -d -p 8080:8080 --name petclinic ${{ env.IMAGE_NAME }}:${{ github.sha }}
           
-      - name: Run OWASP ZAP full scan
-        uses: zaproxy/action-full-scan@v0.10.0
-        with:
-          target: "http://localhost:8080"
-          # rules_file_name: '.zap/rules.tsv'
-          cmd_options: '-a'
+  #     - name: Run OWASP ZAP full scan
+  #       uses: zaproxy/action-full-scan@v0.10.0
+  #       with:
+  #         target: "http://localhost:8080"
+  #         # rules_file_name: '.zap/rules.tsv'
+  #         cmd_options: '-a'
           
-      - name: Evaluate ZAP Results
-        id: zap-results
-        run: |
-          high_alerts=$(grep -c "high:" report_html.html)
-          if (( $high_alerts < 5 )); then
-            echo "::error::ZAP scan failed - high alerts exceed threshold" 
-            exit 1
-          fi
+  #     - name: Evaluate ZAP Results
+  #       id: zap-results
+  #       run: |
+  #         high_alerts=$(grep -c "high:" report_html.html)
+  #         if (( $high_alerts < 5 )); then
+  #           echo "::error::ZAP scan failed - high alerts exceed threshold" 
+  #           exit 1
+  #         fi
           
-  deploy:
-    runs-on: ubuntu-20.04
-    needs: [scan, zap-scan]  
-    steps:
-      - name: Deploy to production 
-        run: |
-          # Add deployment steps here  
-          echo "Deploying Spring Petclinic application to production"
+  # deploy:
+  #   runs-on: ubuntu-20.04
+  #   needs: [scan, zap-scan]  
+  #   steps:
+  #     - name: Deploy to production 
+  #       run: |
+  #         # Add deployment steps here  
+  #         echo "Deploying Spring Petclinic application to production"
